name: Daily Digest Scheduler

on:
  schedule:
    - cron: '0 6 * * 1-5'  # 8 AM CET (6 AM UTC) Monday-Friday
  workflow_dispatch:  # Allow manual triggering

jobs:
  send-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Send Daily Digest
        run: |
          echo "Calling: ${{ secrets.DATABUTTON_API_URL }}"
          response=$(curl -s -w "\nHTTP_CODE:%{http_code}\n" \
            -X POST "${{ secrets.DATABUTTON_API_URL }}" \
            -H "Content-Type: application/json")
          
          echo "Response:"
          echo "$response"
          
          # Extract HTTP code
          http_code=$(echo "$response" | grep "HTTP_CODE:" | cut -d: -f2)
          
          if [ "$http_code" != "200" ]; then
            echo "Error: HTTP $http_code"
            exit 1
          else
            echo "Success: Daily digest sent!"
          fi
