name: Daily Digest Scheduler

on:
  schedule:
    # Runs at 8 AM UTC (3 AM EST, 4 AM EDT) Monday-Friday
    - cron: '0 8 * * 1-5'  # 8 AM UTC on weekdays only
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Send Daily Digest
        run: |
          echo "Calling: https://api.databutton.com/_projects/b00d9010-cdb3-45e2-aa8f-131e1567a9e4/dbtn/prodx/app/routes/daily-digest/generate-digest"
          response=$(curl -s -w "HTTP_CODE:%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            "https://api.databutton.com/_projects/b00d9010-cdb3-45e2-aa8f-131e1567a9e4/dbtn/prodx/app/routes/daily-digest/generate-digest")
          
          http_code=$(echo "$response" | grep -o "HTTP_CODE:[0-9]*" | cut -d: -f2)
          body=$(echo "$response" | sed 's/HTTP_CODE:[0-9]*$//')
          
          echo "Response: $body"
          echo "HTTP Code: $http_code"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: HTTP $http_code"
            exit 1
          else
            echo "Success: Daily digest sent!"
          fi
