name: Daily Digest Scheduler

on:
  schedule:
    - cron: '0 8 * * *'  # 8 AM UTC (morning digest)
    - cron: '0 20 * * *' # 8 PM UTC (evening digest)
  workflow_dispatch: # Allows manual trigger

jobs:
  send-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Send Daily Digest
        run: |
          curl -X POST "${{ secrets.DATABUTTON_API_URL }}/daily-digest/generate-digest" \
            -H "Content-Type: application/json" \
            -w "Status: %{http_code}\nResponse: %{response}" \
            -s
