name: Daily Digest Scheduler

on:
  schedule:
    - cron: "0 8 * * 1-5"
  workflow_dispatch:

jobs:
  send-digest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Send Daily Digest
        run: |
          echo "Calling: ${{ secrets.DATABUTTON_API_URL }}/generate-digest"
          response=$(curl -s -w "HTTP_CODE:%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            --max-time 1200 \
            --retry 2 \
            --retry-delay 60 \
            ${{ secrets.DATABUTTON_API_URL }}/generate-digest
          
          http_code=$(echo "$response" | grep -o "HTTP_CODE:[0-9]*" | cut -d: -f2)
          body=$(echo "$response" | sed 's/HTTP_CODE:[0-9]*$//')
          
          echo "Response: $body"
          echo "HTTP Code: $http_code"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error: HTTP $http_code"
            exit 1
          else
            echo "Success: Daily digest sent!"
          fi
